from django.urls import path

from . import views


urlpatterns = [
    path("health/", views.health_check, name="health_check"),
    path("auth/register/", views.auth_register, name="auth_register"),
    path("auth/register/verify/", views.auth_register_verify, name="auth_register_verify"),
    path("auth/login/", views.auth_login, name="auth_login"),
    path("auth/google/", views.auth_google, name="auth_google"),
    path("auth/refresh/", views.auth_refresh, name="auth_refresh"),
    path("auth/me/", views.auth_me, name="auth_me"),
    path("auth/profile/", views.auth_profile, name="auth_profile"),
    path("ai/listing-review/", views.ai_listing_review, name="ai_listing_review"),
    path("ai/maintenance-triage/", views.ai_maintenance_triage, name="ai_maintenance_triage"),
    path("ai/application-score/", views.ai_application_score, name="ai_application_score"),
    path("users/", views.users_collection, name="users_collection"),
    path("users/<int:user_id>/rental-history/", views.user_rental_history, name="user_rental_history"),
    path("users/<int:supplier_id>/follow/", views.supplier_follow, name="supplier_follow"),
    path("properties/", views.properties_collection, name="properties_collection"),
    path("properties/<int:property_id>/", views.property_detail, name="property_detail"),
    path("properties/<int:property_id>/view/", views.property_view, name="property_view"),
    path("properties/<int:property_id>/comments/", views.property_comments_collection, name="property_comments_collection"),
    path("properties/<int:property_id>/photos/", views.property_photos_collection, name="property_photos_collection"),
    path("properties/<int:property_id>/videos/", views.property_videos_collection, name="property_videos_collection"),
    path("properties/<int:property_id>/save/", views.saved_properties_collection, name="saved_properties_collection"),
    path("applications/", views.applications_collection, name="applications_collection"),
    path("applications/<int:application_id>/", views.application_detail, name="application_detail"),
    path("payments/", views.payments_collection, name="payments_collection"),
    path("payments/<int:payment_id>/reminder/", views.payment_reminder, name="payment_reminder"),
    path("leases/", views.leases_collection, name="leases_collection"),
    path("leases/<int:lease_id>/sign/", views.lease_sign, name="lease_sign"),
    path("maintenance/", views.maintenance_collection, name="maintenance_collection"),
    path("maintenance/<int:maintenance_id>/", views.maintenance_detail, name="maintenance_detail"),
    path("verifications/", views.verifications_collection, name="verifications_collection"),
    path("verifications/<int:verification_id>/review/", views.verification_review, name="verification_review"),
    path("viewings/", views.viewings_collection, name="viewings_collection"),
    path("viewings/<int:viewing_id>/", views.viewing_detail, name="viewing_detail"),
    path("conversations/", views.conversations_collection, name="conversations_collection"),
    path("conversations/<int:conversation_id>/", views.conversation_detail, name="conversation_detail"),
    path("conversations/<int:conversation_id>/messages/", views.conversation_messages, name="conversation_messages"),
    path("conversations/<int:conversation_id>/calls/", views.conversation_calls, name="conversation_calls"),
    path("conversations/<int:conversation_id>/calls/<int:call_id>/", views.conversation_call_detail, name="conversation_call_detail"),
    path("reviews/", views.reviews_collection, name="reviews_collection"),
    path("reports/", views.reports_collection, name="reports_collection"),
    path("reports/<int:report_id>/", views.report_detail, name="report_detail"),
    path("commissions/", views.commissions_collection, name="commissions_collection"),
    path("analytics/landlords/<int:user_id>/", views.landlord_analytics, name="landlord_analytics"),
]
