# Generated by Django 6.0.7 on 2026-07-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('listing_risk', 'Listing risk'), ('maintenance_triage', 'Maintenance triage'), ('application_score', 'Application score')], max_length=32)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('provider', models.CharField(default='local', max_length=40)),
                ('model', models.CharField(default='property24-rules-v1', max_length=80)),
                ('score', models.JSONField(blank=True, default=dict)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('recommendation', models.CharField(blank=True, max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['analysis_type', 'target_type', 'target_id'], name='rentals_aia_analysi_21419f_idx')],
            },
        ),
    ]
