# Generated by Django 6.0.7 on 2026-08-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_phone_verification_and_identity_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='address_gps_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='country_of_residence',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='declaration_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='document_issue_country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='document_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='politically_exposed_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='privacy_notice_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='proof_of_address_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='proof_of_address_document',
            field=models.FileField(blank=True, upload_to='verification/address/'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='residential_address',
            field=models.TextField(blank=True),
        ),
    ]
