# Generated by Django 6.0.7 on 2026-08-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0015_verificationrequest_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='document_retention_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='id_number_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='verification_method',
            field=models.CharField(default='local_ocr', max_length=40),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='verification_provider',
            field=models.CharField(default='local_ocr', max_length=80),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='verification_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ocr_complete', 'OCR complete'), ('validation', 'Validation'), ('verified', 'Verified'), ('manual_review', 'Manual review'), ('failed', 'Failed'), ('expired', 'Expired'), ('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=16),
        ),
    ]
