# Generated by Django 6.0.7 on 2026-08-14 12:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0016_verificationrequest_document_retention_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
