# Generated by Django 6.0.7 on 2026-08-16 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0019_message_client_message_id_message_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/assets/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='media/thumbnails/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=16)),
                ('scope', models.CharField(choices=[('profile', 'Profile'), ('property', 'Property'), ('chat', 'Chat'), ('maintenance', 'Maintenance'), ('verification', 'Verification'), ('lease', 'Lease')], max_length=24)),
                ('access', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=12)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('original_name', models.CharField(blank=True, max_length=180)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('source_model', models.CharField(blank=True, max_length=80)),
                ('source_id', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'scope', 'status'], name='rentals_med_owner_i_c2f7e9_idx'), models.Index(fields=['source_model', 'source_id'], name='rentals_med_source__a59a05_idx'), models.Index(fields=['media_type', 'created_at'], name='rentals_med_media_t_e210d2_idx')],
            },
        ),
    ]
