# Generated by Django 6.0.7 on 2026-09-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0020_mediaasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_sqft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
