# Generated by Django 6.0.7 on 2026-09-20 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0022_property_show_exact_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='area_sqft',
        ),
        migrations.CreateModel(
            name='PropertyHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='rentals.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['property', 'expires_at'], name='property_hold_active_idx'), models.Index(fields=['tenant', 'expires_at'], name='property_hold_tenant_idx')],
            },
        ),
    ]
