# Generated by Codex on 2026-09-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0023_remove_property_area_sqft_propertyhold"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agent_is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="agent_permissions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="parent_landlord",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "landlord"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_agent_accounts",
                to="rentals.user",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("rented", "Rented"),
                    ("sold", "Sold"),
                ],
                db_index=True,
                default="available",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="listing_intent",
            field=models.CharField(
                choices=[("rent", "For rent"), ("sale", "For sale")],
                db_index=True,
                default="rent",
                max_length=12,
            ),
        ),
    ]
