# Generated by Django 6.0.7 on 2026-09-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0028_land_listing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('flat', 'Flat'), ('cottage', 'Cottage'), ('student_accommodation', 'Student accommodation'), ('commercial_property', 'Commercial property'), ('land', 'Land / Stand')], max_length=32),
        ),
    ]
