# Generated by Django 6.0.7 on 2026-10-05 21:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0035_viewing_rejected_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySearchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_query', models.CharField(max_length=1000)),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('modifications', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='neighborhoodprofile',
            new_name='rentals_nei_city_bfcd87_idx',
            old_name='rentals_nei_city_3d22d5_idx',
        ),
        migrations.RenameIndex(
            model_name='propertycomparison',
            new_name='rentals_pro_tenant__4057e7_idx',
            old_name='rentals_pro_tenant_35739d_idx',
        ),
        migrations.RenameIndex(
            model_name='propertylike',
            new_name='rentals_pro_propert_127d33_idx',
            old_name='rentals_pro_property_2cae0c_idx',
        ),
        migrations.RenameIndex(
            model_name='savedsearch',
            new_name='rentals_sav_tenant__11c775_idx',
            old_name='rentals_sav_tenant_95bb2b_idx',
        ),
        migrations.RenameIndex(
            model_name='savedsearchmatch',
            new_name='rentals_sav_saved_s_ed819a_idx',
            old_name='rentals_sav_search_7e97f3_idx',
        ),
        migrations.RenameIndex(
            model_name='savedsearchmatch',
            new_name='rentals_sav_propert_b826a8_idx',
            old_name='rentals_sav_property_5281c9_idx',
        ),
        migrations.AddField(
            model_name='propertysearchsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_search_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='propertysearchsession',
            index=models.Index(fields=['user', '-updated_at'], name='rentals_pro_user_id_acc30e_idx'),
        ),
    ]
