# Generated by Django 6.0.7 on 2026-10-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0036_property_search_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='accommodation_institution',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='property',
            name='shared_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('flat', 'Flat'), ('cottage', 'Cottage'), ('room', 'Room'), ('office', 'Office'), ('shop', 'Shop'), ('student_accommodation', 'Student accommodation'), ('commercial_property', 'Commercial property'), ('land', 'Land / Stand')], max_length=32),
        ),
    ]
