# Generated by Django 6.0.7 on 2026-10-08 15:37

from django.db import migrations, models


def normalize_legacy_marketplace_choices(apps, schema_editor):
    ServiceListing = apps.get_model("rentals", "ServiceListing")
    JobPosting = apps.get_model("rentals", "JobPosting")
    ServiceListing.objects.filter(price_type__in=["daily", "negotiable"]).update(price_type="quote")
    JobPosting.objects.filter(employment_type__in=["casual", "internship"]).update(
        employment_type="temporary"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0041_jobposting_jobapplication_servicelisting_and_more'),
    ]

    operations = [
        migrations.RunPython(
            normalize_legacy_marketplace_choices,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract'), ('temporary', 'Temporary')], max_length=16),
        ),
        migrations.AlterField(
            model_name='servicelisting',
            name='price_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('hourly', 'Hourly'), ('quote', 'Quote')], max_length=16),
        ),
    ]
