# Generated by Django 6.0.7 on 2026-10-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0042_alter_jobposting_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistrationotp',
            name='marketplace_capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='marketplace_capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
