const zimbabweInstitutions = <String>[
  'Africa University',
  'Arrupe Jesuit University',
  'Bindura University of Science Education (BUSE)',
  'Bulawayo Polytechnic',
  'Catholic University of Zimbabwe',
  'Chinhoyi University of Technology (CUT)',
  'Great Zimbabwe University (GZU)',
  'Gweru Polytechnic',
  'Harare Institute of Technology (HIT)',
  'Harare Polytechnic',
  'Kwekwe Polytechnic',
  'Lupane State University',
  'Manicaland State University of Applied Sciences',
  'Masvingo Polytechnic',
  'Midlands State University (MSU)',
  'Mutare Polytechnic',
  'National University of Science and Technology (NUST)',
  'Reformed Church University',
  'Solusi University',
  'University of Zimbabwe (UZ)',
  "Women's University in Africa",
  'Zimbabwe Ezekiel Guti University',
  'Zimbabwe Open University (ZOU)',
  'Zimbabwe School of Mines',
];
